
package TESTE_PROG06_AnaLanca;

import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author AnaLanca
 */
public class A_AreaDoTrapezio_Ana extends javax.swing.JFrame {

    /**
     * Creates new form A_AreaDoTrapezio_Ana
     */
    public A_AreaDoTrapezio_Ana()
    {        
        super("Área do Trapézio");
        Container panel1 = getContentPane();
        setLayout(null);        
        initComponents();
        lblErro.setVisible(false);
        
        btnCalcular.addActionListener(
            new ActionListener()
                {
                    public void actionPerformed(ActionEvent evt)
                    {
                        float baseMaior = 0, baseMenor = 0, altura = 0, area = 0;   
                        boolean num1OK = true, num2OK = true, num3OK = true;

                        //validar 1º numero
                        try
                        {
                            baseMaior = Float.parseFloat(txtBaseMaior.getText());
                        }
                        catch(NumberFormatException e)
                        {
                            lblErro.setVisible(true);
                            lblErro.setText("O primeiro número não é válido!"); 
                            num1OK = false;
                        }

                        //validar 2º numero
                        try
                        {
                            baseMenor = Float.parseFloat(txtBaseMenor.getText());
                        }
                        catch(NumberFormatException e)
                        {
                            lblErro.setVisible(true);
                            if(num1OK)
                            {
                                lblErro.setText("O segundo número não é válido!");
                            }                                               
                            num2OK = false;
                        }
                        
                        //validar 3º numero
                        try
                        {
                            altura = Float.parseFloat(txtAltura.getText());
                        }
                        catch(NumberFormatException e)
                        {
                            lblErro.setVisible(true);
                            if(num1OK && num2OK)
                            {
                                lblErro.setText("O terceiro número não é válido!");
                            }
                            else
                            {
                                lblErro.setText("Não inseriu nenhum número válido!"); 
                            }                    
                            num3OK = false;
                        }
                        
                        //verificar os operações de cálculos     
                        if(num1OK==true && num2OK==true && num3OK==true)
                        {
                            area = ((baseMaior + baseMenor) * altura)/2;
                            txtArea.setText(String.valueOf(area));
                              
                        }      
                    }    
                });
        
        btnLimpar.addActionListener(
        new ActionListener(){
            public void actionPerformed(ActionEvent e){
                txtBaseMaior.setText(null);
                txtBaseMenor.setText(null);
                txtAltura.setText(null);
                txtArea.setText(null);
                txtBaseMaior.requestFocus();               
            }        
        });
        
        btnSair.addActionListener(
        new ActionListener(){
            public void actionPerformed(ActionEvent e){
                System.exit(0);
            }
        });
        
       
        setVisible(true);
        setSize(500,390);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        txtArea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBaseMaior = new javax.swing.JTextField();
        txtBaseMenor = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(null);
        panel1.add(txtArea);
        txtArea.setBounds(161, 188, 117, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Área do Trapézio");
        panel1.add(jLabel1);
        jLabel1.setBounds(144, 11, 134, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Base maior:");
        panel1.add(jLabel2);
        jLabel2.setBounds(80, 70, 71, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Base menor:");
        panel1.add(jLabel3);
        jLabel3.setBounds(74, 108, 77, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Altura:");
        panel1.add(jLabel4);
        jLabel4.setBounds(111, 146, 40, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Área:");
        panel1.add(jLabel5);
        jLabel5.setBounds(119, 188, 32, 17);
        panel1.add(txtBaseMaior);
        txtBaseMaior.setBounds(161, 70, 117, 20);
        panel1.add(txtBaseMenor);
        txtBaseMenor.setBounds(161, 108, 117, 20);
        panel1.add(txtAltura);
        txtAltura.setBounds(161, 146, 117, 20);

        btnCalcular.setText("Calcular");
        panel1.add(btnCalcular);
        btnCalcular.setBounds(53, 286, 101, 23);

        btnLimpar.setText("Limpar");
        panel1.add(btnLimpar);
        btnLimpar.setBounds(164, 286, 101, 23);

        btnSair.setText("Sair");
        panel1.add(btnSair);
        btnSair.setBounds(275, 286, 101, 23);
        panel1.add(lblErro);
        lblErro.setBounds(53, 245, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    public static void main(String args[]) {
        A_AreaDoTrapezio_Ana app = new A_AreaDoTrapezio_Ana();
        app.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblErro;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtBaseMaior;
    private javax.swing.JTextField txtBaseMenor;
    // End of variables declaration//GEN-END:variables
}
