
package TESTE_PROG06_AnaLanca;

import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;

/**
 *
 * @author Ana Lança
 */
public class C_RegraDeSinal_Ana extends javax.swing.JFrame
{    
    public C_RegraDeSinal_Ana() {
        super("Regra de Sinal");
        Container panel1 = getContentPane();
        setLayout(null);     
        
        initComponents();
        ButtonGroup grupo;
        lblResposta.setVisible(false);
        
        grupo = new ButtonGroup();
        grupo.add(rbtnResp1);
        grupo.add(rbtnResp2);
        grupo.add(rbtnResp3);        
        
        btnTestar.addActionListener(
            new ActionListener()
                {
                    public void actionPerformed(ActionEvent evt)
                    {
                        lblResposta.setVisible(true);
                        if(rbtnResp2.isSelected()== true)
                        {                            
                            lblResposta.setForeground(Color.GREEN);
                            lblResposta.setText("Parabéns! Resposta correta!");
                        }
                        else if(rbtnResp1.isSelected()== true ||
                                rbtnResp3.isSelected()== true)
                        {                            
                            lblResposta.setForeground(Color.red);
                            lblResposta.setText("Que pena! Resposta incorreta!");
                        }                
                    }
            });
                
        
        btnLimpar.addActionListener(
        new ActionListener(){
            public void actionPerformed(ActionEvent e){
                grupo.clearSelection();  
                lblResposta.setVisible(false);
            }        
        });

        btnSair.addActionListener(
        new ActionListener(){
            public void actionPerformed(ActionEvent e){
                System.exit(0);
            }
        });
        
        
        setVisible(true);
        setSize(500,500);
        setLocationRelativeTo(null);     
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbtnResp1 = new javax.swing.JRadioButton();
        rbtnResp2 = new javax.swing.JRadioButton();
        rbtnResp3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTestar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblResposta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Regra de Sinal");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 210, 29);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TESTE_PROG06_AnaLanca/sinaStop.JPG"))); // NOI18N
        lblImg.setText("jLabel2");
        jPanel1.add(lblImg);
        lblImg.setBounds(40, 50, 152, 152);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("O que fazer ao ver este sinal de trânsito?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 210, 290, 50);
        jPanel1.add(rbtnResp1);
        rbtnResp1.setBounds(20, 270, 21, 21);
        jPanel1.add(rbtnResp2);
        rbtnResp2.setBounds(20, 300, 21, 21);
        jPanel1.add(rbtnResp3);
        rbtnResp3.setBounds(20, 330, 21, 21);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Avançar sem olhar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 270, 160, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Parar, e se seguro avançar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 300, 210, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Avançar se seguro");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 330, 180, 14);

        btnTestar.setText("Testar");
        jPanel1.add(btnTestar);
        btnTestar.setBounds(20, 410, 106, 23);

        btnLimpar.setText("Limpar");
        jPanel1.add(btnLimpar);
        btnLimpar.setBounds(150, 410, 106, 23);

        btnSair.setText("Sair");
        jPanel1.add(btnSair);
        btnSair.setBounds(290, 410, 107, 23);

        lblResposta.setText("...");
        jPanel1.add(lblResposta);
        lblResposta.setBounds(20, 370, 296, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TESTE_PROG06_AnaLanca/sinais2.JPG"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 520, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_RegraDeSinal_Ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_RegraDeSinal_Ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_RegraDeSinal_Ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_RegraDeSinal_Ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_RegraDeSinal_Ana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JRadioButton rbtnResp1;
    private javax.swing.JRadioButton rbtnResp2;
    private javax.swing.JRadioButton rbtnResp3;
    // End of variables declaration//GEN-END:variables
}
